'use client';

import { useState, useEffect, useCallback, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import BoardSelector from '@/components/BoardSelector';
import BurndownChart from '@/components/BurndownChart';
import CompletedIssuesList from '@/components/CompletedIssuesList';
import SprintIssuesList from '@/components/SprintIssuesList';
import DailyChangesList from '@/components/DailyChangesList';
import { TimeData, CompletedIssuesByDate, JiraIssue, DailyChangeSummary } from '@/types/jira';
import { useSettings } from '@/contexts/SettingsContext';
import { useTranslation } from '@/locales/translations';

function HomeContent() {
  const { settings, isJiraConfigured, setTimeCalculationMethod } = useSettings();
  const t = useTranslation(settings.language);
  const searchParams = useSearchParams();

  // URL params
  const urlBoardIds = searchParams.get('boardIds');
  const urlMethod = searchParams.get('method');
  const urlAutoGenerate = searchParams.get('auto');

  const [selectedBoardIds, setSelectedBoardIds] = useState<string[]>([]);
  const [initialBoardIds, setInitialBoardIds] = useState<string[] | null>(null);
  const [burndownData, setBurndownData] = useState<{
    timeline: TimeData[];
    totalEstimate: number;
    totalSpent: number;
  }>({
    timeline: [],
    totalEstimate: 0,
    totalSpent: 0,
  });
  const [completedIssues, setCompletedIssues] = useState<CompletedIssuesByDate[]>([]);
  const [dailyChanges, setDailyChanges] = useState<DailyChangeSummary[]>([]);
  const [sprintInfo, setSprintInfo] = useState<Array<{ boardId: string; sprintName: string; startDate?: string; endDate?: string }>>([]);
  const [sprintDates, setSprintDates] = useState<{ startDate?: string; endDate?: string }>({});
  const [allSprintIssues, setAllSprintIssues] = useState<JiraIssue[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [statusMessages, setStatusMessages] = useState<string[]>([]);

  // Parse URL params on mount
  useEffect(() => {
    // Set time calculation method from URL
    if (urlMethod && (urlMethod === 'original' || urlMethod === 'remaining')) {
      setTimeCalculationMethod(urlMethod);
    }

    // Parse board IDs from URL
    if (urlBoardIds) {
      const boards = urlBoardIds
        .split(/[,\s]+/)
        .map(id => id.trim())
        .filter(id => id.length > 0);
      if (boards.length > 0) {
        setInitialBoardIds(boards);
        setSelectedBoardIds(boards);
      }
    }
  }, [urlBoardIds, urlMethod, setTimeCalculationMethod]);

  const handleGenerateChart = useCallback(async (boardIds?: string[]) => {
    const boards = boardIds || selectedBoardIds;

    if (boards.length === 0) {
      setError('Please select at least one board');
      return;
    }

    if (!isJiraConfigured) {
      setError(t('jiraNotConfigured'));
      return;
    }

    try {
      setLoading(true);
      setError(null);
      setStatusMessages([]);

      const response = await fetch('/api/burndown-stream', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          boardIds: boards,
          domain: settings.jiraConfig.domain,
          email: settings.jiraConfig.email,
          apiToken: settings.jiraConfig.apiToken,
          calculationMethod: settings.timeCalculationMethod,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate burndown chart');
      }

      if (!response.body) {
        throw new Error('No response body');
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();

        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          if (!line.trim()) continue;

          try {
            const message = JSON.parse(line);

            if (message.type === 'status') {
              setStatusMessages(prev => [...prev, message.message]);
            } else if (message.type === 'error') {
              setStatusMessages(prev => [...prev, `❌ ${message.message}`]);
            } else if (message.type === 'data') {
              const data = message.data;
              setBurndownData({
                timeline: data.timeline,
                totalEstimate: data.totalEstimate,
                totalSpent: data.totalSpent,
              });
              setCompletedIssues(data.completedIssuesByDate || []);
              setDailyChanges(data.dailyChanges || []);
              setSprintInfo(data.sprintInfo || []);
              setSprintDates({
                startDate: data.sprintStartDate,
                endDate: data.sprintEndDate,
              });
              setAllSprintIssues(data.allIssues || []);
            }
          } catch (parseError) {
            console.error('Failed to parse message:', line, parseError);
          }
        }
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  }, [selectedBoardIds, isJiraConfigured, settings, t]);

  // Auto-generate chart if URL params are provided and auto=true
  useEffect(() => {
    if (
      !hasAutoGenerated &&
      initialBoardIds &&
      initialBoardIds.length > 0 &&
      isJiraConfigured &&
      urlAutoGenerate === 'true'
    ) {
      setHasAutoGenerated(true);
      handleGenerateChart(initialBoardIds);
    }
  }, [hasAutoGenerated, initialBoardIds, isJiraConfigured, urlAutoGenerate, handleGenerateChart]);

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 transition-colors duration-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100 font-heading">
            {t('appTitle')}
          </h1>
          <p className="mt-2 text-gray-600 dark:text-gray-400">
            {t('appSubtitle')}
          </p>

        </div>

        {/* Board Selection */}
        <div className="mb-6">
          <BoardSelector
            onBoardsSelected={setSelectedBoardIds}
            initialBoardIds={initialBoardIds || undefined}
          />
        </div>

        {/* Generate Button */}
        <div className="mb-6">
          <button
            onClick={() => handleGenerateChart()}
            disabled={loading || selectedBoardIds.length === 0}
            className={`w-full sm:w-auto px-6 py-3 rounded-lg font-medium text-white transition-all duration-200 ${loading || selectedBoardIds.length === 0
              ? 'bg-gray-400 dark:bg-gray-600 cursor-not-allowed'
              : 'bg-primary hover:bg-primary-700 shadow-md hover:shadow-lg'
              }`}
          >
            {loading ? (
              <span className="flex items-center justify-center">
                <svg
                  className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  ></circle>
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                  ></path>
                </svg>
                {t('generatingChart')}
              </span>
            ) : (
              t('generateChart')
            )}
          </button>

          {selectedBoardIds.length === 0 && (
            <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
              {t('enterBoardHint')}
            </p>
          )}
        </div>

        {/* Status Messages */}
        {loading && statusMessages.length > 0 && (
          <div className="mb-6 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4 max-h-64 overflow-y-auto">
            <div className="flex items-center gap-2 mb-3">
              <svg
                className="animate-spin h-4 w-4 text-blue-600 dark:text-blue-400"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
              >
                <circle
                  className="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  strokeWidth="4"
                ></circle>
                <path
                  className="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                ></path>
              </svg>
              <p className="text-sm font-semibold text-blue-900 dark:text-blue-100">
                Processing...
              </p>
            </div>
            <div className="space-y-1 font-mono text-xs">
              {statusMessages.map((msg, index) => (
                <div
                  key={index}
                  className={`text-blue-800 dark:text-blue-300 ${
                    msg.startsWith('❌') ? 'text-red-600 dark:text-red-400' : ''
                  }`}
                >
                  {msg}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Error Message */}
        {error && (
          <div className="mb-6 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4">
            <p className="text-red-800 dark:text-red-300">{error}</p>
          </div>
        )}
        {sprintInfo.length > 0 && (
          <div className="mt-3 space-y-2">
            <div className="flex flex-wrap gap-2">
              {sprintInfo.map((info, index) => (
                <span
                  key={index}
                  className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-300 border border-green-200 dark:border-green-800"
                >
                  Board {info.boardId}: {info.sprintName}
                </span>
              ))}
            </div>
            {sprintDates.startDate && (
              <div className="text-sm text-gray-600 dark:text-gray-400">
                <span className="font-medium">{t('sprintTimeline')}:</span>{' '}
                {new Date(sprintDates.startDate).toLocaleDateString(settings.language === 'vi' ? 'vi-VN' : 'en-US', {
                  day: '2-digit',
                  month: '2-digit',
                  year: 'numeric',
                })}{' '}
                -{' '}
                {sprintDates.endDate
                  ? new Date(sprintDates.endDate).toLocaleDateString(settings.language === 'vi' ? 'vi-VN' : 'en-US', {
                    day: '2-digit',
                    month: '2-digit',
                    year: 'numeric',
                  })
                  : t('noEndDate')}
              </div>
            )}
          </div>
        )}
        {/* Burndown Chart */}
        <BurndownChart
          timeline={burndownData.timeline}
          totalEstimate={burndownData.totalEstimate}
          totalSpent={burndownData.totalSpent}
          allIssues={allSprintIssues}
        />

        {/* Sprint Issues List */}
        {allSprintIssues.length > 0 && (
          <div className="mt-6">
            <SprintIssuesList issues={allSprintIssues} />
          </div>
        )}

        {/* Daily Changes List */}
        {dailyChanges.length > 0 && (
          <div className="mt-6">
            <DailyChangesList dailyChanges={dailyChanges} />
          </div>
        )}

        {/* Completed Issues List */}
        {completedIssues.length > 0 && (
          <div className="mt-6">
            <CompletedIssuesList completedIssuesByDate={completedIssues} />
          </div>
        )}
      </div>
    </div>
  );
}

export default function Home() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto"></div>
          <p className="mt-4 text-gray-600 dark:text-gray-400">Loading...</p>
        </div>
      </div>
    }>
      <HomeContent />
    </Suspense>
  );
}
